name: 01-buliding Blocks
on: push
jobs:
    echo-heloo:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "hello satya"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Successful step
              run:  |
                echo "i will success"
                 exit 0
            - name: say-goodbye
              run: echo "goodbye"        
